server:
  port: 9999
  context-path: /services
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8888/services/user

spring:
  zipkin:
    base-url: http://localhost:8080
  sleuth:
    sampler:
      percentage: 1.0
    
logging:
  level:
    org.springframework.cloud.sleuth: DEBUG
