server:
  port: 9090
  context-path: /services
  
security:
  oauth2:
    client:
      access-token-uri: http://localhost:9999/spring-security-oauth-server/oauth/token
      user-authorization-uri: http://localhost:9999/spring-security-oauth-server/oauth/authorize
      client-id: commandlineinterface
      client-secret: commandlineinterface
    resource:
      user-info-uri: http://localhost:9999/spring-security-oauth-server/user
      
spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ACCOUNT_DB
    username: rdurgesh
    password: rdurgesh
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  zipkin:
    base-url: http://localhost:7777
  sleuth:
    sampler:
      percentage: 1.0
      
logging:
  level:
    org.springframework.web: ERROR
    org.springframework.cloud.sleuth: ERROR
    org.springframework.security: ERROR